# Generated by Django 3.1.1 on 2020-10-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(default='Dar es Salaam', max_length=50),
        ),
    ]
