# Generated by Django 3.1.1 on 2021-02-21 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='comment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
