# Generated by Django 3.1.1 on 2021-03-15 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_posted',)},
        ),
    ]
